"use client"

import { useState } from "react"
import { Undo2, Redo2, Copy, Download, Check, FileText, File } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"

interface ScriptEditorProps {
  content: string
  title?: string
}

export function ScriptEditor({ content, title = "Untitled Script" }: ScriptEditorProps) {
  const [hasCopied, setHasCopied] = useState(false)

  // Quick helper to strip HTML tags for raw text output
  const getRawText = () => {
    if (typeof document === "undefined") return content
    const tempDiv = document.createElement("div")
    tempDiv.innerHTML = content
    return tempDiv.textContent || tempDiv.innerText || ""
  }

  const handleCopy = async () => {
    const text = getRawText()
    try {
      await navigator.clipboard.writeText(text)
      setHasCopied(true)
      setTimeout(() => setHasCopied(false), 2000)
    } catch (err) {
      console.error("Failed to copy", err)
    }
  }

  const handleDownload = () => {
    const text = getRawText()
    const blob = new Blob([text], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'vidzara-script'}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handlePdfExport = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: 'Inter', system-ui, sans-serif; color: #111; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px; }
            h1 { font-size: 24px; font-weight: 700; margin-bottom: 30px; text-align: center; color: #000; border-bottom: 1px solid #eee; padding-bottom: 16px; }
            h3 { font-size: 18px; font-weight: 600; margin-top: 24px; margin-bottom: 12px; color: #222; }
            p { font-size: 15px; margin-bottom: 16px; color: #333; }
            strong { font-weight: 600; color: #000; }
            .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #eee; text-align: center; font-size: 13px; color: #666; font-weight: 500; }
            @media print {
              @page { margin: 0; }
              body { padding: 2cm; max-width: 100%; }
              .footer { position: fixed; bottom: 1.5cm; left: 0; right: 0; border: none; }
            }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          ${content}
          
          <div class="footer">
             Generated by vidzara.com
          </div>

          <script>
            window.onload = () => {
              window.print();
              setTimeout(() => window.close(), 500);
            }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }

  return (
    <div className="flex flex-col h-full rounded-2xl border border-border/40 bg-card/30 backdrop-blur-sm overflow-hidden">
      {/* Toolbar */}
      <div className="flex justify-between items-center px-3 py-1.5 border-b border-border/40">
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon" disabled className="size-8 text-muted-foreground hover:text-foreground opacity-50 cursor-not-allowed">
            <Undo2 className="size-4" />
          </Button>
          <Button variant="ghost" size="icon" disabled className="size-8 text-muted-foreground hover:text-foreground opacity-50 cursor-not-allowed">
            <Redo2 className="size-4" />
          </Button>
        </div>
        <div className="flex items-center gap-1">
          <Button 
            variant="ghost" 
            size="sm" 
            onClick={handleCopy}
            className="text-muted-foreground hover:text-foreground gap-1.5"
            title="Copy Text"
          >
            {hasCopied ? <Check className="size-4 text-emerald-500" /> : <Copy className="size-4" />}
            <span className="hidden sm:inline">{hasCopied ? "Copied" : "Copy"}</span>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button 
                variant="ghost" 
                size="sm" 
                className="text-muted-foreground hover:text-foreground gap-1.5"
                title="Download Script"
              >
                <Download className="size-4" />
                <span className="hidden sm:inline">Download</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-48">
              <DropdownMenuItem onClick={handleDownload} className="gap-2 cursor-pointer">
                <FileText className="size-4" />
                <span>Download as Text</span>
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handlePdfExport} className="gap-2 cursor-pointer">
                <File className="size-4" />
                <span>Download as PDF</span>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
      
      {/* Editor Area */}
      <div className="p-5 sm:p-6 lg:p-8 flex-1 overflow-y-auto">
        <div 
          className="max-w-3xl mx-auto [&>h3]:text-foreground [&>h3]:font-semibold [&>h3]:text-base [&>h3]:mb-2 [&>h3]:mt-6 [&>h3:first-child]:mt-0 [&>p]:text-muted-foreground/90 [&>p]:text-[15px] [&>p]:leading-relaxed [&>p]:mb-4 last:[&>p]:mb-0 [&>strong]:text-foreground [&>strong]:font-semibold"
          dangerouslySetInnerHTML={{ __html: content }} 
        />
      </div>
    </div>
  )
}
